<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="adminPanel.aspx.cs" Inherits="Portfolio_in_asp.portfolio.WebForm2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 1143px;
            height: 495px;
        }
        /* External CSS file - style.css */

/* External CSS file - style.css */

/* Style for the form container */
#form1 {
    margin: auto; /* Center the form horizontally */
    width: 80%; /* Set the width of the form */
    max-width: 1143px; /* Set the maximum width */
    margin-top: 50px; /* Add margin at the top to push it down */
    position: relative; /* Make it relative to its containing block */
}

/* Style for the logout button */
#Button1 {
    height: 31px;
    width: 78px;
    background-color: #007bff; /* Blue background color */
    color: #fff; /* White text color */
    border: none; /* Remove button border */
    cursor: pointer; /* Change cursor to pointer on hover */
    font-size: 16px; /* Font size */
    position: absolute; /* Position it absolutely */
    bottom: 500px; /* Set distance from the bottom */
    right: -20px; /* Set distance from the right */
}

/* Style for the logout button on hover */
#Button1:hover {
    background-color: #0056b3; /* Darker blue background color */
}


        .auto-style2 {
            right: 280px;
            bottom: 91px;
        }
        .auto-style3 {
            left: -6px;
            top: 5px;
        }


    </style>
</head>
<body>
    <form id="form1" runat="server" class="auto-style3">
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" CellPadding="2" DataKeyNames="Id" DataSourceID="SqlDataSource1" ForeColor="Black" GridLines="None" Height="293px" Width="555px" ShowFooter="True">
                <AlternatingRowStyle BackColor="PaleGoldenrod" />
                <Columns>
                    <asp:TemplateField HeaderText="Id" InsertVisible="False" SortExpression="Id">
                        <EditItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Eval("Id") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:LinkButton OnClick="LinkButton1_Click" ValidationGroup="Insert" ID="LinkButton1" runat="server">Insert</asp:LinkButton>
                        </FooterTemplate>

                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="name" SortExpression="name">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("name") %>'></asp:TextBox>
                            <asp:RequiredFieldValidator ControlToValidate="TextBox1" ForeColor="Aqua" Text="*" SetFocusOnError="true" ID="RequiredFieldValidator1" runat="server" ErrorMessage="Name is a required field"></asp:RequiredFieldValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label2" runat="server" Text='<%# Bind("name") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="footername" runat="server"></asp:TextBox>
                            <asp:RequiredFieldValidator ValidationGroup="Insert" ControlToValidate="footername" ForeColor="Aqua" Text="*" SetFocusOnError="true" ID="RequiredFieldValidator2" runat="server" ErrorMessage="Name is  required "></asp:RequiredFieldValidator>
                        </FooterTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="feild" SortExpression="feild">
                        <EditItemTemplate>
                              <asp:DropDownList ID="dropdownlist1" runat="server" Text='<%# Bind("feild") %>'>
     <asp:ListItem>Select feild</asp:ListItem>
     <asp:ListItem>NLP</asp:ListItem>
     <asp:ListItem>image processing</asp:ListItem>
     <asp:ListItem>cryptography</asp:ListItem>
 </asp:DropDownList>
                         <asp:RequiredFieldValidator  InitialValue="select feild" ControlToValidate="dropdownlist1" ForeColor="Aqua" Text="*" SetFocusOnError="true" ID="RequiredFieldValidator3" runat="server" ErrorMessage="field is required"></asp:RequiredFieldValidator>
 

                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label3" runat="server" Text='<%# Bind("feild") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:DropDownList ID="footerdropdownlistfeild" runat="server">
                                <asp:ListItem>Select feild</asp:ListItem>
                                <asp:ListItem>NLP</asp:ListItem>
                                <asp:ListItem>image processing</asp:ListItem>
                                <asp:ListItem>cryptography</asp:ListItem>
                            </asp:DropDownList>
                             <asp:RequiredFieldValidator ValidationGroup="Insert" InitialValue="select feild" ControlToValidate="footerdropdownlistfeild" ForeColor="Aqua" Text="*" SetFocusOnError="true" ID="RequiredFieldValidator4" runat="server" ErrorMessage="field is required"></asp:RequiredFieldValidator>
 

                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="reason" SortExpression="reason">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("reason") %>'></asp:TextBox>
                        <asp:RequiredFieldValidator InitialValue="select feild" ControlToValidate="TextBox3" ForeColor="Aqua" Text="*" SetFocusOnError="true" ID="RequiredFieldValidator5" runat="server" ErrorMessage="reason is required"></asp:RequiredFieldValidator>
 
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label4" runat="server" Text='<%# Bind("reason") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="footerreason" runat="server"></asp:TextBox>
                        <asp:RequiredFieldValidator ValidationGroup="Insert" InitialValue="select feild" ControlToValidate="footerreason" ForeColor="Aqua" Text="*" SetFocusOnError="true" ID="RequiredFieldValidator6" runat="server" ErrorMessage="reason is required"></asp:RequiredFieldValidator>
 
                        </FooterTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="Tan" />
                <HeaderStyle BackColor="Tan" Font-Bold="True" />
                <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
                <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
                <SortedAscendingCellStyle BackColor="#FAFAE7" />
                <SortedAscendingHeaderStyle BackColor="#DAC09E" />
                <SortedDescendingCellStyle BackColor="#E1DB9C" />
                <SortedDescendingHeaderStyle BackColor="#C2A47B" />
            </asp:GridView>
            <asp:ValidationSummary ValidationGroup="Insert" ID="ValidationSummary1" runat="server" BackColor="White" />
            <asp:ValidationSummary  ID="ValidationSummary2" runat="server" BackColor="White" />
        </div>
        <p class="auto-style1">
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [interested] WHERE [Id] = @Id" InsertCommand="INSERT INTO [interested] ([name], [feild], [reason]) VALUES (@name, @feild, @reason)" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [interested]" UpdateCommand="UPDATE [interested] SET [name] = @name, [feild] = @feild, [reason] = @reason WHERE [Id] = @Id">
                <DeleteParameters>
                    <asp:Parameter Name="Id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="feild" Type="String" />
                    <asp:Parameter Name="reason" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="feild" Type="String" />
                    <asp:Parameter Name="reason" Type="String" />
                    <asp:Parameter Name="Id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <asp:Button ID="Button1" runat="server" Height="31px" OnClick="Button1_Click" Text="Logout" Width="78px" CssClass="auto-style2" />
        </p>
    </form>
</body>
</html>
